services:
  db:
    networks:
      - db-vuda-net
    image: mysql:8.0
    restart: always
    container_name: db_vuda
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - ./configuration/db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 50001:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p root"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      

volumes:
  mysql:

networks:
  db-vuda-net:
    driver: bridge
    external: true
